spring:
  application:
    name: kafka-consumer-avro
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      value-deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
      properties:
        apicurio.registry.url: http://localhost:8080/apis/registry/v2
        apicurio.registry.auto-register: false
        apicurio.registry.find-latest: true
        apicurio.registry.enable.confluent.id.handler: true

---

consumer.group-id:
  customers: dev.debezium-cdc.public.customers

---

server:
  port: 9000
